[newjersey/doula-pm#460] Attempt to block automerge on all end-to-end tests passing
Previously, https://github.com/org-njdhs-mahs/doula-medicaid/pull/485 was automerged, even though an end-to-end test failed, and the required end-to-end-tests-all-complete job was skipped.

Other people seems to have encountered this, where automerge does not block when `needs:` dependencies fail: https://github.com/orgs/community/discussions/28864

Attempting the solution in https://github.com/orgs/community/discussions/28864#discussioncomment-13644151

This commit contributes to newjersey/doula-pm#460.

diff --git a/.github/workflows/end_to_end_tests.yml b/.github/workflows/end_to_end_tests.yml
--- a/.github/workflows/end_to_end_tests.yml
+++ b/.github/workflows/end_to_end_tests.yml
@@ -40,6 +40,7 @@ jobs:
       cypress_run_command: cypress:run -- --env websiteUnavailable=true
 
   end-to-end-tests-all-complete:
+    if: ${{ always() }}
     needs:
       [
         end-to-end-tests-development-flags,
@@ -49,5 +50,9 @@ jobs:
       ]
     runs-on: ubuntu-latest
     steps:
-      - name: To detect that required e2e tests are complete
-        run: echo "All e2e tests have passed"
+      - name: Fail unless required checks pass
+        if:
+          ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') ||
+          contains(needs.*.result, 'skipped') }}
+        run: exit 1
+      - run: 'echo "✅ All required jobs have passed!"'
